version: "3.9"

services:
  app:
    build:
      context: ./client
    image: app
    container_name: employee-app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    depends_on:
      - web

  db:
    image: mongo
    container_name: db
    volumes:
      - db-data:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

  web:
    build:
      context: ./server
    container_name: employee-web
    ports:
      - "7000:7000"
    depends_on:
      - db
    environment:
      NODE_ENV: production
      MONGO_USERNAME: admin
      MONGO_PASSWORD: password
      MONGO_HOST: db
      MONGO_PORT: "27017"
      WAIT_HOSTS: db:27017

volumes:
  db-data:
